name: .NET Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: >
        dotnet publish DesktopClient/DesktopClient.csproj
        -c Release
        -r osx-x64
        -p:PublishReadyToRun=true
        -p:PublishSingleFile=true
        -p:IncludeNativeLibrariesForSelfExtract=true
        --self-contained true
    - uses: actions/upload-artifact@v2
      with:
        name: InvestmentAnalyzer.osx-x64
        path: DesktopClient/bin/Release/net6.0/osx-x64/publish/
